language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly
  
before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

notifications:
  email:
    - alfshek@hotmail.com
